### ISSUE TITLE
SFSArray:getBool returning null on iOS (+ suggested fix)

### ISSUE THREAD

**Issue by rewb0rn** [boorik/smartfox-haxe-client#13]
Hello,

when compiling the library with Air for iOS (Objective C, not interpreter), the function SFSArray::getBool is always returning null at the moment.

This is the original line that causes a problem:
`return(wrapper != null ?cast(wrapper.data,Bool):null);`

 I was testing a bit and this is the easiest way to fix it:

`return(wrapper != null ?cast(wrapper.data):null);`  

I can prepare a pull request, do you have any concerns or another preferred fix? 

Just a sidenote: iOS with Air builds have some of these mystery bugs from time to time, due to the fact that the compilation works differently on the platform (no AVM). We have seen some rare and strange issues in AS3 code on iOS as well, before we started using Haxe.

**Comment by boorik** [comment]
Hi,
This fix is really strange. Only unsafe cast works???
This must not have any side effects on other targets. You can send a PR.
But this is really odd.

**Comment by boorik** [comment]
Merged.
Thank you
