### ISSUE TITLE
Bluebox

### ISSUE THREAD

**Issue by rewb0rn** [boorik/smartfox-haxe-client#15]
Hi boorik,

is the bluebox protocol currently supported? In our tests it looks like it's not working, but I wanted to check first before we start diving into building it ourselves. Our games are live now with the API and we have a few user complaints that they can not play anymore.

Thanks,
Ruben

**Comment by rewb0rn** [comment]
Ok one of our diligent devs has fixed it, I will create the pull request now.

**Comment by boorik** [comment]
Hi,
Great! 
Well I didn't use bluebox that's why I didn't finish the port.
