### ISSUE TITLE
Property iterator not found on haxe.ds.IntMap

### ISSUE THREAD

**Issue by rewb0rn** [boorik/smartfox-haxe-client#3]
Hello,

we are seeing this exception when trying to use the SFS2X Haxe API. Is this a known issue, maybe an incompatibility to the latest Haxe version?

Thanks in advance,
Ruben

`[Fault] exception, information=ReferenceError: Error #1069: Property iterator not found on haxe.ds.IntMap and there is no default value.

Lambda$/array at C:\HaxeToolkit\haxe\std\Lambda.hx:46
com.smartfoxserver.v2.entities.managers::SFSUserManager/getUserList at O:\wd\SFS2X_AS3_API_source\src\com\smartfoxserver\v2\entities\managers\SFSUserManager.as:120
com.smartfoxserver.v2.entities::SFSRoom/get userList at O:\wd\SFS2X_AS3_API_source\src\com\smartfoxserver\v2\entities\SFSRoom.as:359
com.smartfoxserver.v2.controllers::SystemController/fnRoomLost at O:\wd\SFS2X_AS3_API_source\src\com\smartfoxserver\v2\controllers\SystemController.as:389
com.smartfoxserver.v2.controllers::SystemController/handleMessage at O:\wd\SFS2X_AS3_API_source\src\com\smartfoxserver\v2\controllers\SystemController.as:139
com.smartfoxserver.v2.core::SFSProtocolCodec/dispatchRequest at O:\wd\SFS2X_AS3_API_source\src\com\smartfoxserver\v2\core\SFSProtocolCodec.as:150
com.smartfoxserver.v2.core::SFSProtocolCodec/onPacketRead at O:\wd\SFS2X_AS3_API_source\src\com\smartfoxserver\v2\core\SFSProtocolCodec.as:54
com.smartfoxserver.v2.core::SFSIOHandler/handlePacketData at O:\wd\SFS2X_AS3_API_source\src\com\smartfoxserver\v2\core\SFSIOHandler.as:252
com.smartfoxserver.v2.core::SFSIOHandler/onDataRead at O:\wd\SFS2X_AS3_API_source\src\com\smartfoxserver\v2\core\SFSIOHandler.as:111
com.smartfoxserver.v2.bitswarm::BitSwarmClient/onSocketData at O:\wd\SFS2X_AS3_API_source\src\com\smartfoxserver\v2\bitswarm\BitSwarmClient.as:454`

**Comment by boorik** [comment]
Hi,
this is a bit weird, I can see in your logs that it use the as3 version of the api : "SFS2X_AS3_API_source\src\com\smartfoxserver\v2\entities\managers\SFSUserManager.as:120"
Can you provide a sample of code that create the exception and the ouput of "haxelib list" command.
Thanks

**Comment by rewb0rn** [comment]
Ah thanks for pointing that out, I completely mixed your library with the one that is listed on haxelib as sfs2x-api. I installed your library now via `haxelib git smartfox-haxe-client https://github.com/boorik/smartfox-haxe-client` and it works! Thank you! :)
