### ISSUE TITLE
Suggestion: Remove ISFSArray, ISFSObject

### ISSUE THREAD

**Issue by rewb0rn** [boorik/smartfox-haxe-client#5]
Hi,

what do you think of removing the interfaces ISFSArray and ISFSObject and instead declaring all functions with SFSArray and SFSObject?

This would improve the constistency with the HTML5 API because in Javascript there are no interfaces. This causes incompatibilities between the HTML5 and all other targets where for example SFSObject.getSFSArray() returns an instance of SFSArray in HTML5 and an instance of ISFSArray on all other targets.

I do not expect any errors or problems from this change. If you agree I could create a merge request in the next days.

**Comment by boorik** [comment]
Hmm why not. We can give it a try and look if there is no drawbacks to this. Rollback will be easy if we encounter issues.

**Comment by boorik** [comment]
merged. Good job :)

**Comment by flashultra** [comment]
What was the point to remove ISFSArray and  ISFSObject ? I understand about javascript API, but this cause problem on other target. At example at the moment I convert source code from AS3 to haxe and In the code it's used many times ISFSObject  . I can replace it with SFSObject , but it won't be the same as documentation . At example:
 1) Flash target
   **ExtensionRequest(extCmd:String, params:ISFSObject = null ....**
  (*)  http://docs2x.smartfoxserver.com/api-docs/asdoc/com/smartfoxserver/v2/requests/ExtensionRequest.html

2) Java API 
  **ExtensionRequest(java.lang.String extCmd, com.smartfoxserver.v2.entities.data.ISFSObject params)** 
(*) http://docs2x.smartfoxserver.com/api-docs/javadoc/client/sfs2x/client/requests/ExtensionRequest.html

3) Objective-C 
 **(id)requestWithExtCmd:(NSString *)extCmd params:(id<ISFSObject>)params room:(id<Room>)room udp:(BOOL)udp**
(*) http://docs2x.smartfoxserver.com/api-docs/objc-doc/Classes/ExtensionRequest.html

Removing ISFSObject  and ISFSArray and you create different API. I understand about javascript, but still at the moment I need to target flash and html5.
 
 Hope so you will revert changes.

**Comment by boorik** [comment]
Yes we can do something else, maybe we can do something like :
#if html5
typedef ISFSObject = SFSObject;
#else
interface ...

**Comment by flashultra** [comment]
That sounds good for me i.e. in Smartfox.hx still will wait for ISFSObject  , but for JS that will be SFSObject

**Comment by boorik** [comment]
Hey, I just pushed a branch named "interfaces", it compiles with flash and html5 targets (didn't try others ). I have an issue recovering policy file in flash.
Can you try it and tell me if you have this issue?
Is it working as expected for you?

**Comment by boorik** [comment]
ok got the issue on my linux machine, on my windows it works with flash too.

**Comment by flashultra** [comment]
The project is still WIP, so I can't make real tests. I will update in the thread when make a test.

**Comment by flashultra** [comment]
On question about  SFSObject class. There have : 
    public function getLong(key:String):Null<Float>
but is that correct ? Long should be Int or maybe I'm wrong ?

**Comment by boorik** [comment]
Regarding the old documentation, Java Long is haxe Float :
[http://old.haxe.org/doc/java/externs](http://old.haxe.org/doc/java/externs)

**Comment by boorik** [comment]
I merged the interfaces branch in the master one.

**Comment by rewb0rn** [comment]
Yes I agree, using typedef for HTML5 might be the better solution, I didn't think of that!
