### ISSUE TITLE
[HTML5] SFSDataSerializer class

### ISSUE THREAD

**Issue by flashultra** [boorik/smartfox-haxe-client#8]
SFSDataSerializer not works correctly (at example object2binary(...) ). I tried to check documentation http://docs2x.smartfoxserver.com/api-docs/jsdoc/client/index.html ,but link for SFSDataSerializer are broken. Should I exposed HTML5  methods or need to rewrite the DefaultSFSDataSerializer class ?

**Comment by boorik** [comment]
Which openfl version are you using?
I'm currently working on an issue with latest versions.
Can you publish a sample of code that I can try to figure out what's going on?

**Comment by flashultra** [comment]
I also use the latest version of Openfl. I sent obejct to Smartfox server and after that return the result as SFSObject . I found the problem. Just in Smartfox javascript api DefaultSFSDataSerializer. wasn't exposed . To do that you should change js file and add SFSDataSerializer there. Here is a sample function  which I use for test: 
```
	public function TestSFSDataSerializer():Void 
	{
		var sfso:ISFSObject = new SFSObject();
		sfso.putLong("tm", Date.now().getTime());
        sfso.putUtfString("data", "TEST");
		 var objSfs:ByteArray = DefaultSFSDataSerializer.instance.object2binary(sfso);
		 
		 var dSfso : ISFSObject = DefaultSFSDataSerializer.instance.binary2object(objSfs);
		 
		 trace("Time: " + dSfso.getLong("tm"));
		 trace("Data: " + dSfso.getUtfString("data"));
	}
```
One more thing. For SFSObect extern all Long calls ( getLong, putLong, getLongArray putLongArray )  should be a Float ?

**Comment by boorik** [comment]
You can try the fix with this code :
```haxe
		var sfso:ISFSObject = new SFSObject();
		var t:Float = Date.now().getTime();
		trace("time before serialization:"+t);
		sfso.putLong("tm",t );
                sfso.putUtfString("data", "TEST");
		var objSfs:openfl.utils.ByteArray = DefaultSFSDataSerializer.getInstance().object2binary(sfso); 
		var dSfso : ISFSObject = DefaultSFSDataSerializer.getInstance().binary2object(objSfs);
		trace("Time: " + dSfso.getLong("tm"));
		trace("Data: " + dSfso.getUtfString("data"));
```
